name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: coinkeeperadmin/coinkeeperpro-pages
          publish_dir: site
          publish_branch: gh-pages
          force_orphan: true
